project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on 1.html
          - text: Hands-on Exercise 2
            href: Hands-on 2.html
          
      - text: In-class Exercises
        menu: 
          - text: In-class Ex1
            href: in-class exercise 1/in-class ex1.html

    right:
      - href: index.html
        text: Home
      - about.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

